name: Workflow Ejercicio2
on: push
jobs:
  Ejercicio2:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      
    steps:
      - name: Analizar calidad de codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
